In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing

In [3]:
col = ['buying','maint','doors','persons','lug_boot','safety','Class_Values']
data1 = pd.read_csv('C:\\Users\\UTSAV\\Desktop\\MY_Practice\\car.data',header= 0 , names = col,index_col = None)
data1.head(2)

buying  maint doors persons lug_boot safety Class_Values
0  vhigh  vhigh     2       2    small    med        unacc
1  vhigh  vhigh     2       2    small   high        unacc

In [4]:
data = data1

In [5]:
data.nunique()
data.safety.unique()

array(['med', 'high', 'low'], dtype=object)

In [6]:
var = preprocessing.LabelEncoder()
buying = var.fit_transform(data1.buying)
maint = var.fit_transform(data1.maint)
lug_boot = var.fit_transform(data1.lug_boot)
safety = var.fit_transform(data1.safety)
Class_Values = var.fit_transform(data1.Class_Values)

In [7]:
data.safety.unique()

array(['med', 'high', 'low'], dtype=object)

In [8]:
data.shape

(1727, 7)

In [26]:
data.tail(70)

buying maint doors persons lug_boot safety Class_Values
1657    low   low     3       4    small   high         good
1658    low   low     3       4      med    low        unacc
1659    low   low     3       4      med    med          acc
1660    low   low     3       4      med   high         good
1661    low   low     3       4      big    low        unacc
1662    low   low     3       4      big    med         good
1663    low   low     3       4      big   high        vgood
1664    low   low     3       5    small    low        unacc
1665    low   low     3       5    small    med          acc
1666    low   low     3       5    small   high         good
1667    low   low     3       5      med    low        unacc
1668    low   low     3       5      med    med         good
1669    low   low     3       5      med   high        vgood
1670    low   low     3       5      big    low        unacc
1671    low   low     3       5      big    med         good
1672    low   low     3       5      big   high        vgood
1673    low   low     4       2    small    low        unacc
1674    low   low     4       2    small    med        unacc
1675    low   low     4       2    small   high        unacc
1676    low   low     4       2      med    low        unacc
1677    low   low     4       2      med    med        unacc
1678    low   low     4       2      med   high        unacc
1679    low   low     4       2      big    low        unacc
1680    low   low     4       2      big    med        unacc
1681    low   low     4       2      big   high        unacc
1682    low   low     4       4    small    low        unacc
1683    low   low     4       4    small    med          acc
1684    low   low     4       4    small   high         good
1685    low   low     4       4      med    low        unacc
1686    low   low     4       4      med    med         good
...     ...   ...   ...     ...      ...    ...          ...
1697    low   low     4       5      big    low        unacc
1698    low   low     4       5      big    med         good
1699    low   low     4       5      big   high        vgood
1700    low   low     5       2    small    low        unacc
1701    low   low     5       2    small    med        unacc
1702    low   low     5       2    small   high        unacc
1703    low   low     5       2      med    low        unacc
1704    low   low     5       2      med    med        unacc
1705    low   low     5       2      med   high        unacc
1706    low   low     5       2      big    low        unacc
1707    low   low     5       2      big    med        unacc
1708    low   low     5       2      big   high        unacc
1709    low   low     5       4    small    low        unacc
1710    low   low     5       4    small    med          acc
1711    low   low     5       4    small   high         good
1712    low   low     5       4      med    low        unacc
1713    low   low     5       4      med    med         good
1714    low   low     5       4      med   high        vgood
1715    low   low     5       4      big    low        unacc
1716    low   low     5       4      big    med         good
1717    low   low     5       4      big   high        vgood
1718    low   low     5       5    small    low        unacc
1719    low   low     5       5    small    med          acc
1720    low   low     5       5    small   high         good
1721    low   low     5       5      med    low        unacc
1722    low   low     5       5      med    med         good
1723    low   low     5       5      med   high        vgood
1724    low   low     5       5      big    low        unacc
1725    low   low     5       5      big    med         good
1726    low   low     5       5      big   high        vgood

[70 rows x 7 columns]

In [10]:
#data.doors.replace('5more',5,inplace = True)
#data.persons.replace('more',5,inplace = True)

In [11]:
#len(data.doors)
for i in range(len(data.doors)):
    if(data['doors'][i] == '5more'):
        data['doors'][i] = 5
    elif(data['doors'][i] == '2'):
        data['doors'][i] = 2 
    elif(data['doors'][i] == '3'):
        data['doors'][i] = 3
    elif(data['doors'][i] == '3'):
        data['doors'][i] = 3
    elif(data['doors'][i] == '4'):
        data['doors'][i] = 4

In [12]:
for i in range(len(data.persons)):
    if(data['persons'][i] == 'more'):
        data['persons'][i] = 5
    elif(data['persons'][i] == '2'):
        data['persons'][i] = 2 
    elif(data['persons'][i] == '3'):
        data['persons'][i] = 3
    elif(data['persons'][i] == '3'):
        data['persons'][i] = 3
    elif(data['persons'][i] == '4'):
        data['persons'][i] = 4

In [13]:
data.head(2)

buying  maint doors persons lug_boot safety Class_Values
0  vhigh  vhigh     2       2    small    med        unacc
1  vhigh  vhigh     2       2    small   high        unacc

In [14]:
data.persons.unique()

array([2, 4, 5], dtype=object)

In [18]:

print(buying)
print(maint)
#print(data.doors)
#print(data.persons)
print(lug_boot)
print(safety)

[3 3 3 ... 1 1 1]
[3 3 3 ... 1 1 1]
[2 2 1 ... 0 0 0]
[2 0 1 ... 1 2 0]


In [19]:
features = list(zip(buying,maint,data.doors,data.persons,lug_boot,safety))
features

[(3, 3, 2, 2, 2, 2),
 (3, 3, 2, 2, 2, 0),
 (3, 3, 2, 2, 1, 1),
 (3, 3, 2, 2, 1, 2),
 (3, 3, 2, 2, 1, 0),
 (3, 3, 2, 2, 0, 1),
 (3, 3, 2, 2, 0, 2),
 (3, 3, 2, 2, 0, 0),
 (3, 3, 2, 4, 2, 1),
 (3, 3, 2, 4, 2, 2),
 (3, 3, 2, 4, 2, 0),
 (3, 3, 2, 4, 1, 1),
 (3, 3, 2, 4, 1, 2),
 (3, 3, 2, 4, 1, 0),
 (3, 3, 2, 4, 0, 1),
 (3, 3, 2, 4, 0, 2),
 (3, 3, 2, 4, 0, 0),
 (3, 3, 2, 5, 2, 1),
 (3, 3, 2, 5, 2, 2),
 (3, 3, 2, 5, 2, 0),
 (3, 3, 2, 5, 1, 1),
 (3, 3, 2, 5, 1, 2),
 (3, 3, 2, 5, 1, 0),
 (3, 3, 2, 5, 0, 1),
 (3, 3, 2, 5, 0, 2),
 (3, 3, 2, 5, 0, 0),
 (3, 3, 3, 2, 2, 1),
 (3, 3, 3, 2, 2, 2),
 (3, 3, 3, 2, 2, 0),
 (3, 3, 3, 2, 1, 1),
 (3, 3, 3, 2, 1, 2),
 (3, 3, 3, 2, 1, 0),
 (3, 3, 3, 2, 0, 1),
 (3, 3, 3, 2, 0, 2),
 (3, 3, 3, 2, 0, 0),
 (3, 3, 3, 4, 2, 1),
 (3, 3, 3, 4, 2, 2),
 (3, 3, 3, 4, 2, 0),
 (3, 3, 3, 4, 1, 1),
 (3, 3, 3, 4, 1, 2),
 (3, 3, 3, 4, 1, 0),
 (3, 3, 3, 4, 0, 1),
 (3, 3, 3, 4, 0, 2),
 (3, 3, 3, 4, 0, 0),
 (3, 3, 3, 5, 2, 1),
 (3, 3, 3, 5, 2, 2),
 (3, 3, 3, 5, 2, 0),
 (3, 3, 3, 5,

In [20]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(features,Class_Values)
predicted= model.predict([[3,3,0,0,2,1]])
print("Predicted Value:", predicted)

Predicted Value: [2]


In [24]:
print(Class_Values)

[2 2 2 ... 2 1 3]


In [288]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features, Class_Values, test_size = 0.09,random_state = 0)

In [289]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(x_train, y_train)
y_pred = gnb.predict(x_test)

In [290]:
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6666666666666666


In [291]:
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[ 7,  0,  9, 21],
       [ 1,  0,  1,  5],
       [ 5,  0, 90, 10],
       [ 0,  0,  0,  7]], dtype=int64)